# ~/.config/starship.toml
"$schema" = 'https://starship.rs/config-schema.json'

# â”€â”€â”€ GLOBAL â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
add_newline = false
command_timeout = 2000

format = """
$directory\
$git_branch$git_status\
$python\
$conda\
$character
"""

right_format = """
$cmd_duration\
$username$hostname\
$nodejs\
$time
"""

# â”€â”€â”€ MODULES â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

[username]
show_always = true
format = '[ $user ]($style)'

[directory]
# fish_style_pwd_dir_length = 20
truncation_length = 10
truncation_symbol = "â€¦"
truncate_to_repo = false

[git_branch]
format = '[ $symbol$branch ]($style)'

[git_status]
format = '[$all_status]($style)'

[python]
symbol = "ğŸ "
format = '[ $symbol$version ]($style)'

[conda]
format = '[ $symbol$environment ]($style)'

[nodejs]
format = '[ $symbol$version ]($style)'

[docker_context]
format = '[ $symbol$context ]($style)'

[hostname]
ssh_only = true
format = '[$hostname]($style)'

[status]
disabled = false
style = "fg:red"
symbol = 'âœ–'
format = '[$symbol $status]($style)'

[cmd_duration]
disabled = false
min_time = 0
style = "fg:green"
format = '[$duration]($style)'

[time]
disabled = false
time_format = "%H:%M"
format = '[ ïº $time ]($style)'

[character]
success_symbol = '[â¯](bold fg:green)'
error_symbol   = '[â¯](bold fg:red)'

[line_break]
disabled = true
